---
- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - role: webservers
      when: '"worker" in ansible_hostname'

- hosts: localhost
  connection: local
  become: yes
  roles:
    - role: dependencies
