---
- hosts: web
  remote_user: vagrant
  become: true
  roles:
    - role: webservers
      when: '"worker" in ansible_hostname'

- hosts: localhost
  connection: local
  become: true
  roles:
    - role: dependencies
