---
- hosts: all
  remote_user: vagrant
  gather_facts: no
  become: true
  roles:
    - role: webservers
      when: '"worker" in inventory_hostname'

- hosts: localhost
  connection: local
  become: true
  roles:
    - role: dependencies
