# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
NodeCount = 2

Vagrant.configure(2) do |config|
  
  # Webservers
  (1..NodeCount).each do |i|
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yaml"
    end
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "centos/7"
      worker.vm.hostname = "worker#{i}.local.net"
      worker.vm.network "private_network", ip: "172.42.42.10#{i}"
      worker.vm.provider "virtualbox" do |v|
        v.name = "worker#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end
